import { OsmType, Region } from "../../../src/generated/prisma/client.js";

import type { SeedBeach } from "./beach-seed.types.js";

const sourceRetrievedAt = "2026-08-28T00:00:00.000Z";

export const kerchPeninsulaBeaches = [
  {
    slug: "shchelkino-beach",
    name: "Пляж Щелкино",
    officialName: "Пляж Щелкино",
    region: Region.KERCH_PENINSULA,
    locality: "Щёлкино",
    coastalLocationSlug: "shchelkino",
    latitude: "45.437004",
    longitude: "35.824262",
    osmType: OsmType.WAY,
    osmId: 309404314n,
    sourceRetrievedAt,
  },
  {
    slug: "riga-beach",
    name: "Пляж Рига",
    officialName: "Пляж Рига",
    region: Region.KERCH_PENINSULA,
    locality: "Щёлкино",
    coastalLocationSlug: "shchelkino",
    latitude: "45.424390",
    longitude: "35.806611",
    osmType: OsmType.WAY,
    osmId: 309410871n,
    sourceRetrievedAt,
  },
  {
    slug: "generalskie-beaches",
    name: "Генеральские пляжи",
    officialName: "Генеральские пляжи",
    region: Region.KERCH_PENINSULA,
    locality: null,
    coastalLocationSlug: "kurortnoe",
    latitude: "45.471062",
    longitude: "36.212350",
    osmType: OsmType.RELATION,
    osmId: 14104069n,
    sourceRetrievedAt,
  },
  {
    slug: "marine-infantry-beach",
    name: "Пляж \"Морской пехоты\"",
    officialName: "Пляж \"Морской пехоты\"",
    region: Region.KERCH_PENINSULA,
    locality: "Курортное",
    coastalLocationSlug: "kurortnoe",
    latitude: "45.474306",
    longitude: "36.311641",
    osmType: OsmType.RELATION,
    osmId: 12829041n,
    sourceRetrievedAt,
  },
  {
    slug: "kerch-city-beach",
    name: "Городской пляж Керчи",
    officialName: "Городской пляж",
    region: Region.KERCH_PENINSULA,
    locality: "Керчь",
    coastalLocationSlug: "kerch-strait",
    latitude: "45.257233",
    longitude: "36.431321",
    osmType: OsmType.WAY,
    osmId: 244075065n,
    sourceRetrievedAt,
  },
  {
    slug: "kerch-youth-beach",
    name: "Пляж \"Молодежный\"",
    officialName: "Пляж \"Молодежный\"",
    region: Region.KERCH_PENINSULA,
    locality: "Керчь",
    coastalLocationSlug: "kerch-strait",
    latitude: "45.352365",
    longitude: "36.522949",
    osmType: OsmType.WAY,
    osmId: 108379918n,
    sourceRetrievedAt,
  },
  {
    slug: "mayak-beach",
    name: "Пляж Маяк",
    officialName: "Пляж Маяк",
    region: Region.KERCH_PENINSULA,
    locality: null,
    coastalLocationSlug: "kerch-strait",
    latitude: "45.392800",
    longitude: "36.630686",
    osmType: OsmType.WAY,
    osmId: 324728241n,
    sourceRetrievedAt,
  },
] as const satisfies readonly SeedBeach[];
