import { OsmType, Region } from "../../../src/generated/prisma/client.js";

import type { SeedBeach } from "./beach-seed.types.js";

const sourceRetrievedAt = "2026-08-20T00:00:00.000Z";
const expansionSourceRetrievedAt = "2026-08-28T00:00:00.000Z";

export const sevastopolBeaches = [
  {
    slug: "kacha-german-gully-beach",
    name: "Пляж Немецкая балка",
    officialName: "Немецкая балка",
    region: Region.SEVASTOPOL,
    locality: null,
    coastalLocationSlug: "kacha",
    latitude: "44.751254",
    longitude: "33.541913",
    osmType: OsmType.WAY,
    osmId: 1019242473n,
    sourceRetrievedAt: expansionSourceRetrievedAt,
  },
  {
    slug: "uchkuevka",
    name: "Пляж Учкуевка",
    officialName: "Учкуевка",
    region: Region.SEVASTOPOL,
    locality: "Севастополь",
    coastalLocationSlug: "sevastopol-north",
    latitude: "44.644844",
    longitude: "33.536119",
    osmType: OsmType.WAY,
    osmId: 130042680n,
    sourceRetrievedAt,
  },
  {
    slug: "lyubimovka",
    name: "Пляж Любимовка",
    officialName: "Любимовка",
    region: Region.SEVASTOPOL,
    locality: "Севастополь",
    coastalLocationSlug: "sevastopol-north",
    latitude: "44.659856",
    longitude: "33.543911",
    osmType: OsmType.WAY,
    osmId: 129971155n,
    sourceRetrievedAt,
  },
  {
    slug: "sevastopol-khrustalny-beach",
    name: "Хрустальный пляж в Севастополе",
    officialName: "Хрустальный пляж",
    region: Region.SEVASTOPOL,
    locality: "Севастополь",
    coastalLocationSlug: "sevastopol-west",
    latitude: "44.616628",
    longitude: "33.517585",
    osmType: OsmType.WAY,
    osmId: 363596604n,
    sourceRetrievedAt: expansionSourceRetrievedAt,
  },
  {
    slug: "sevastopol-victory-park-beach",
    name: "Пляж Парк Победы в Севастополе",
    officialName: "Пляж «Парк Победы»",
    region: Region.SEVASTOPOL,
    locality: "Севастополь",
    coastalLocationSlug: "sevastopol-west",
    latitude: "44.609213",
    longitude: "33.456287",
    osmType: OsmType.WAY,
    osmId: 91331964n,
    sourceRetrievedAt: expansionSourceRetrievedAt,
  },
  {
    slug: "omega",
    name: "Пляж Омега",
    officialName: "Пляж Омега",
    region: Region.SEVASTOPOL,
    locality: "Севастополь",
    coastalLocationSlug: "sevastopol-west",
    latitude: "44.597638",
    longitude: "33.444116",
    osmType: OsmType.WAY,
    osmId: 230870022n,
    sourceRetrievedAt,
  },
  {
    slug: "yashmovyy",
    name: "Яшмовый пляж",
    officialName: "Яшмовый пляж",
    region: Region.SEVASTOPOL,
    locality: "Севастополь",
    coastalLocationSlug: "fiolent",
    latitude: "44.503340",
    longitude: "33.507753",
    osmType: OsmType.WAY,
    osmId: 410891199n,
    sourceRetrievedAt,
  },
  {
    slug: "balaklava-vasili-beach",
    name: "Пляж Васили у Балаклавы",
    officialName: "Васили",
    region: Region.SEVASTOPOL,
    locality: "Балаклава",
    coastalLocationSlug: "balaklava",
    latitude: "44.492139",
    longitude: "33.578085",
    osmType: OsmType.WAY,
    osmId: 133239652n,
    sourceRetrievedAt: expansionSourceRetrievedAt,
  },
] as const satisfies readonly SeedBeach[];
