import { OsmType, Region } from "../../../src/generated/prisma/client.js";

import type { SeedBeach } from "./beach-seed.types.js";

const sourceRetrievedAt = "2026-08-20T00:00:00.000Z";
const expansionSourceRetrievedAt = "2026-08-28T00:00:00.000Z";

export const westCrimeaBeaches = [
  {
    slug: "chernomorskoe-city-beach",
    name: "Городской пляж Черноморского",
    officialName: "Городской пляж",
    region: Region.WEST_CRIMEA,
    locality: "Черноморское",
    coastalLocationSlug: "chernomorskoe",
    latitude: "45.515397",
    longitude: "32.709091",
    osmType: OsmType.WAY,
    osmId: 241117129n,
    sourceRetrievedAt: expansionSourceRetrievedAt,
  },
  {
    slug: "olenevka-miami",
    name: "Пляж Майами",
    officialName: "Пляж Майами",
    region: Region.WEST_CRIMEA,
    locality: "Оленевка",
    coastalLocationSlug: "olenevka",
    latitude: "45.370471",
    longitude: "32.515378",
    osmType: OsmType.RELATION,
    osmId: 7110570n,
    sourceRetrievedAt,
  },
  {
    slug: "mezhvodnoe-city-beach",
    name: "Городской пляж Межводного",
    officialName: "Городской пляж",
    region: Region.WEST_CRIMEA,
    locality: "Межводное",
    coastalLocationSlug: "mezhvodnoe",
    latitude: "45.577484",
    longitude: "32.844174",
    osmType: OsmType.RELATION,
    osmId: 14050780n,
    sourceRetrievedAt: expansionSourceRetrievedAt,
  },
  {
    slug: "mezhvodnoe-liman-beach",
    name: "Пляж Лиман в Межводном",
    officialName: "Лиман, пляж",
    region: Region.WEST_CRIMEA,
    locality: "Межводное",
    coastalLocationSlug: "mezhvodnoe",
    latitude: "45.569328",
    longitude: "32.857484",
    osmType: OsmType.WAY,
    osmId: 129710030n,
    sourceRetrievedAt: expansionSourceRetrievedAt,
  },
  {
    slug: "popovka",
    name: "Пляж Поповка",
    officialName: "Пляж Поповка",
    region: Region.WEST_CRIMEA,
    locality: "Поповка",
    coastalLocationSlug: "popovka",
    latitude: "45.296314",
    longitude: "33.030565",
    osmType: OsmType.RELATION,
    osmId: 7114030n,
    sourceRetrievedAt,
  },
  {
    slug: "evpatoria-solyaris-beach",
    name: "Пляж Солярис в Евпатории",
    officialName: "Солярис",
    region: Region.WEST_CRIMEA,
    locality: "Евпатория",
    coastalLocationSlug: "evpatoria",
    latitude: "45.198208",
    longitude: "33.387880",
    osmType: OsmType.RELATION,
    osmId: 2881399n,
    sourceRetrievedAt: expansionSourceRetrievedAt,
  },
  {
    slug: "evpatoria-azure-coast-beach",
    name: "Пляж Лазурный берег в Евпатории",
    officialName: "Пляж «Лазурный берег»",
    region: Region.WEST_CRIMEA,
    locality: "Евпатория",
    coastalLocationSlug: "evpatoria",
    latitude: "45.175292",
    longitude: "33.320527",
    osmType: OsmType.WAY,
    osmId: 133393141n,
    sourceRetrievedAt: expansionSourceRetrievedAt,
  },
  {
    slug: "zaozernoe-settlement-beach",
    name: "Поселковый пляж Заозёрного",
    officialName: "Поселковый пляж",
    region: Region.WEST_CRIMEA,
    locality: "Заозёрное",
    coastalLocationSlug: "zaozernoe",
    latitude: "45.158594",
    longitude: "33.293971",
    osmType: OsmType.WAY,
    osmId: 1110686646n,
    sourceRetrievedAt: expansionSourceRetrievedAt,
  },
  {
    slug: "nikolaevka-skif",
    name: "Пляж Скиф",
    officialName: "Пляж Скиф",
    region: Region.WEST_CRIMEA,
    locality: "Николаевка",
    coastalLocationSlug: "nikolaevka",
    latitude: "44.959945",
    longitude: "33.604369",
    osmType: OsmType.WAY,
    osmId: 230611686n,
    sourceRetrievedAt,
  },
] as const satisfies readonly SeedBeach[];
